# build model

In [8]:
%pip install pandas
%pip install numpy

Collecting pandas
  Downloading pandas-3.0.3-cp312-cp312-win_amd64.whl.metadata (19 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.4.6-cp312-cp312-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\gaurawa mihiranga\appdata\roaming\python\python312\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2026.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\gaurawa mihiranga\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.3-cp312-cp312-win_amd64.whl (9.8 MB)
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.8 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.8 MB 1.3 MB/s eta 0:00:08
   ---- ----------------------------------- 1.0/9.8 MB 1.4 MB/s eta 0:00:07
   ----- ---------------------------------- 1.3/9.8 MB 1.3 MB/s eta 0:00:07
   ------ --------------------------------- 1.6/9.8 MB 1.4 MB/s eta 0:00:07
   -------- ------------------------------- 2.1/9.8 MB 1.5 MB/s eta 0:00:05
   --------- ------------------------------ 2.4/9.8 MB 1.5 MB/s eta 0:00:06
   ----------- ---------------------------- 2.9/9.8 MB 1.6 MB/s eta 0:00:05
   ------------- -------------------------- 3.4/9.8 MB 1.7 MB/s eta 0:00:04
   ---------------- ----------------------- 3.9/9.8 MB 1.8 MB/s eta 0:00:04
   ------------------- -------------------- 4.7/9.8 MB 1.9 MB/s eta 0:00:03
   --------------------- ------------------ 5.2/9.8 MB 2.0 MB/s eta 0:00:03
   ------------------------ --------------- 6.0/9.8 MB 2.1 MB/s eta 0:00:02
   --------------------------- ------------ 6.8/9.8 MB 2.2 MB/s eta 0:00:02
   ------------------------------ --------- 7.3/9.8 MB 2.3 MB/s eta 0:00:02
   --------------------------------- ------ 8.1/9.8 MB 2.3 MB/s eta 0:00:01
   ----------------------------------- ---- 8.7/9.8 MB 2.4 MB/s eta 0:00:01
   -------------------------------------- - 9.4/9.8 MB 2.4 MB/s eta 0:00:01
   ---------------------------------------- 9.8/9.8 MB 2.4 MB/s eta 0:00:00
Downloading numpy-2.4.6-cp312-cp312-win_amd64.whl (12.3 MB)
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.3 MB 3.4 MB/s eta 0:00:04
   --- ------------------------------------ 1.0/12.3 MB 2.4 MB/s eta 0:00:05
   ----- ---------------------------------- 1.8/12.3 MB 2.9 MB/s eta 0:00:04
   -------- ------------------------------- 2.6/12.3 MB 3.1 MB/s eta 0:00:04
   ----------- ---------------------------- 3.4/12.3 MB 3.4 MB/s eta 0:00:03
   ------------- -------------------------- 4.2/12.3 MB 3.5 MB/s eta 0:00:03
   ----------------- ---------------------- 5.2/12.3 MB 3.7 MB/s eta 0:00:02
   ------------------- -------------------- 6.0/12.3 MB 3.7 MB/s eta 0:00:02
   --------------------- ------------------ 6.6/12.3 MB 3.6 MB/s eta 0:00:02
   ---------------------- ----------------- 7.1/12.3 MB 3.5 MB/s eta 0:00:02
   ------------------------- -------------- 7.9/12.3 MB 3.4 MB/s eta 0:00:02
   --------------------------- ------------ 8.4/12.3 MB 3.4 MB/s eta 0:00:02
   ---------------------------- ----------- 8.7/12.3 MB 3.4 MB/s eta 0:00:02
   ------------------------------ --------- 9.4/12.3 MB 3.2 MB/s eta 0:00:01
   -------------------------------- ------- 10.0/12.3 MB 3.2 MB/s eta 0:00:01
   ---------------------------------- ----- 10.7/12.3 MB 3.2 MB/s eta 0:00:01
   -------------------------------------- - 11.8/12.3 MB 3.3 MB/s eta 0:00:01
   ---------------------------------------- 12.3/12.3 MB 3.3 MB/s eta 0:00:00
Downloading tzdata-2026.2-py2.py3-none-any.whl (349 kB)
Installing collected packages: tzdata, numpy, pandas
Successfully installed numpy-2.4.6 pandas-3.0.3 tzdata-2026.2
Note: you may need to restart the kernel to use updated packages.

  WARNING: The scripts f2py.exe and numpy-config.exe are installed in 'c:\Users\Gaurawa Mihiranga\AppData\Local\Programs\Python\Python312\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 24.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: numpy in c:\users\gaurawa mihiranga\appdata\local\programs\python\python312\lib\site-packages (2.4.6)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [9]:
import pandas as pd

In [10]:
import numpy as np

In [11]:
data = pd.read_csv('heart_disease.csv')
data.head()

,Age,Gender,Blood Pressure,Cholesterol Level,Exercise Habits,Smoking,Family Heart Disease,Diabetes,BMI,High Blood Pressure,...,High LDL Cholesterol,Alcohol Consumption,Stress Level,Sleep Hours,Sugar Consumption,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level,Heart Disease Status
0,56.0,Male,153.0,155.0,High,Yes,Yes,No,24.991591,Yes,...,No,High,Medium,7.633228,Medium,342.0,NaN,12.969246,12.387250,No
1,69.0,Female,146.0,286.0,High,No,Yes,Yes,25.221799,No,...,No,Medium,High,8.744034,Medium,133.0,157.0,9.355389,19.298875,No
2,46.0,Male,126.0,216.0,Low,No,No,No,29.855447,No,...,Yes,Low,Low,4.440440,Low,393.0,92.0,12.709873,11.230926,No
3,32.0,Female,122.0,293.0,High,Yes,Yes,No,24.130477,Yes,...,Yes,Low,High,5.249405,High,293.0,94.0,12.509046,5.961958,No
4,60.0,Male,166.0,242.0,Low,Yes,Yes,Yes,20.486289,Yes,...,No,Low,High,7.030971,High,263.0,154.0,10.381259,8.153887,No

In [12]:
data.shape

(10000, 21)

In [8]:
data.isnull().sum()

Age                     0
Gender                  0
Blood Pressure          0
Cholesterol Level       0
Exercise Habits         0
Smoking                 0
Family Heart Disease    0
Diabetes                0
BMI                     0
High Blood Pressure     0
Low HDL Cholesterol     0
High LDL Cholesterol    0
Alcohol Consumption     0
Stress Level            0
Sleep Hours             0
Sugar Consumption       0
Triglyceride Level      0
Fasting Blood Sugar     0
CRP Level               0
Homocysteine Level      0
Heart Disease Status    0
dtype: int64

In [13]:
# drop null raws
data = data.dropna()

In [7]:
data.isnull().sum()

Age                     0
Gender                  0
Blood Pressure          0
Cholesterol Level       0
Exercise Habits         0
Smoking                 0
Family Heart Disease    0
Diabetes                0
BMI                     0
High Blood Pressure     0
Low HDL Cholesterol     0
High LDL Cholesterol    0
Alcohol Consumption     0
Stress Level            0
Sleep Hours             0
Sugar Consumption       0
Triglyceride Level      0
Fasting Blood Sugar     0
CRP Level               0
Homocysteine Level      0
Heart Disease Status    0
dtype: int64

In [14]:
data.shape

(7067, 21)

In [15]:
data.info()

<class 'pandas.DataFrame'>
Index: 7067 entries, 1 to 9999
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Age                   7067 non-null   float64
 1   Gender                7067 non-null   str
 2   Blood Pressure        7067 non-null   float64
 3   Cholesterol Level     7067 non-null   float64
 4   Exercise Habits       7067 non-null   str
 5   Smoking               7067 non-null   str
 6   Family Heart Disease  7067 non-null   str
 7   Diabetes              7067 non-null   str
 8   BMI                   7067 non-null   float64
 9   High Blood Pressure   7067 non-null   str
 10  Low HDL Cholesterol   7067 non-null   str
 11  High LDL Cholesterol  7067 non-null   str
 12  Alcohol Consumption   7067 non-null   str
 13  Stress Level          7067 non-null   str
 14  Sleep Hours           7067 non-null   float64
 15  Sugar Consumption     7067 non-null   str
 16  Triglyceride Level    7067 non-null   float64
 17  Fasting Blood Sugar   7067 non-null   float64
 18  CRP Level             7067 non-null   float64
 19  Homocysteine Level    7067 non-null   float64
 20  Heart Disease Status  7067 non-null   str
dtypes: float64(9), str(12)
memory usage: 1.2 MB

In [16]:
data['Heart Disease Status'] = data['Heart Disease Status'].map({'Yes': 1, 'No': 0})

In [17]:
numeric_data = data.select_dtypes(include=['int64', 'float64'])
numeric_data.corr()['Heart Disease Status']

Age                    -0.006233
Blood Pressure         -0.019111
Cholesterol Level       0.008652
BMI                     0.021957
Sleep Hours             0.007656
Triglyceride Level      0.011631
Fasting Blood Sugar     0.001399
CRP Level              -0.005395
Homocysteine Level      0.011784
Heart Disease Status    1.000000
Name: Heart Disease Status, dtype: float64

In [18]:
data.tail()

,Age,Gender,Blood Pressure,Cholesterol Level,Exercise Habits,Smoking,Family Heart Disease,Diabetes,BMI,High Blood Pressure,...,High LDL Cholesterol,Alcohol Consumption,Stress Level,Sleep Hours,Sugar Consumption,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level,Heart Disease Status
9992,68.0,Female,169.0,291.0,Medium,Yes,No,No,22.839718,No,...,No,Medium,Low,6.057509,High,299.0,142.0,3.321020,11.910244,1
9994,73.0,Female,144.0,191.0,Medium,Yes,Yes,Yes,39.459620,No,...,No,Medium,Low,7.549114,Medium,200.0,88.0,1.154904,8.021732,1
9995,25.0,Female,136.0,243.0,Medium,Yes,No,No,18.788791,Yes,...,Yes,Medium,High,6.834954,Medium,343.0,133.0,3.588814,19.132004,1
9998,23.0,Male,142.0,299.0,Low,Yes,No,Yes,34.964026,Yes,...,Yes,Medium,High,8.526329,Medium,113.0,153.0,7.215634,11.873486,1
9999,38.0,Female,128.0,193.0,Medium,Yes,Yes,Yes,25.111295,No,...,Yes,High,Medium,5.659394,High,121.0,149.0,14.387810,6.208531,1

In [19]:
data.tail()

,Age,Gender,Blood Pressure,Cholesterol Level,Exercise Habits,Smoking,Family Heart Disease,Diabetes,BMI,High Blood Pressure,...,High LDL Cholesterol,Alcohol Consumption,Stress Level,Sleep Hours,Sugar Consumption,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level,Heart Disease Status
9992,68.0,Female,169.0,291.0,Medium,Yes,No,No,22.839718,No,...,No,Medium,Low,6.057509,High,299.0,142.0,3.321020,11.910244,1
9994,73.0,Female,144.0,191.0,Medium,Yes,Yes,Yes,39.459620,No,...,No,Medium,Low,7.549114,Medium,200.0,88.0,1.154904,8.021732,1
9995,25.0,Female,136.0,243.0,Medium,Yes,No,No,18.788791,Yes,...,Yes,Medium,High,6.834954,Medium,343.0,133.0,3.588814,19.132004,1
9998,23.0,Male,142.0,299.0,Low,Yes,No,Yes,34.964026,Yes,...,Yes,Medium,High,8.526329,Medium,113.0,153.0,7.215634,11.873486,1
9999,38.0,Female,128.0,193.0,Medium,Yes,Yes,Yes,25.111295,No,...,Yes,High,Medium,5.659394,High,121.0,149.0,14.387810,6.208531,1

In [20]:
data['Gender'] = data['Gender'].replace({'Male': 1, 'Female': 0})

In [21]:
data.head()

,Age,Gender,Blood Pressure,Cholesterol Level,Exercise Habits,Smoking,Family Heart Disease,Diabetes,BMI,High Blood Pressure,...,High LDL Cholesterol,Alcohol Consumption,Stress Level,Sleep Hours,Sugar Consumption,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level,Heart Disease Status
1,69.0,0,146.0,286.0,High,No,Yes,Yes,25.221799,No,...,No,Medium,High,8.744034,Medium,133.0,157.0,9.355389,19.298875,0
2,46.0,1,126.0,216.0,Low,No,No,No,29.855447,No,...,Yes,Low,Low,4.440440,Low,393.0,92.0,12.709873,11.230926,0
3,32.0,0,122.0,293.0,High,Yes,Yes,No,24.130477,Yes,...,Yes,Low,High,5.249405,High,293.0,94.0,12.509046,5.961958,0
4,60.0,1,166.0,242.0,Low,Yes,Yes,Yes,20.486289,Yes,...,No,Low,High,7.030971,High,263.0,154.0,10.381259,8.153887,0
5,25.0,1,152.0,257.0,Low,Yes,No,No,28.144681,No,...,No,Low,Medium,5.504876,Low,126.0,91.0,4.297575,10.815983,0

In [22]:
data['Smoking'] = data['Smoking'].replace({'Yes': 1, 'No': 0})
data['Family Heart Disease'] = data['Family Heart Disease'].replace({'Yes': 1, 'No': 0})
data['Diabetes'] = data['Diabetes'].replace({'Yes': 1, 'No': 0})
data['High Blood Pressure'] = data['High Blood Pressure'].replace({'Yes': 1, 'No': 0})
data['Low HDL Cholesterol'] = data['Low HDL Cholesterol'].replace({'Yes': 1, 'No': 0})
data['High LDL Cholesterol'] = data['High LDL Cholesterol'].replace({'Yes': 1, 'No': 0})
data['Exercise Habits'] = data['Exercise Habits'].replace({'High': 3, 'Medium':2, 'Low':1, 'None': 0})
data['Alcohol Consumption'] = data['Alcohol Consumption'].replace({'High': 3, 'Medium':2, 'Low':1, 'None': 0})
data['Stress Level'] = data['Stress Level'].replace({'High': 3, 'Medium':2, 'Low':1, 'None': 0})
data['Sugar Consumption'] = data['Sugar Consumption'].replace({'High': 3, 'Medium':2, 'Low':1, 'None': 0})

In [23]:
data.head()

,Age,Gender,Blood Pressure,Cholesterol Level,Exercise Habits,Smoking,Family Heart Disease,Diabetes,BMI,High Blood Pressure,...,High LDL Cholesterol,Alcohol Consumption,Stress Level,Sleep Hours,Sugar Consumption,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level,Heart Disease Status
1,69.0,0,146.0,286.0,3,0,1,1,25.221799,0,...,0,2,3,8.744034,2,133.0,157.0,9.355389,19.298875,0
2,46.0,1,126.0,216.0,1,0,0,0,29.855447,0,...,1,1,1,4.440440,1,393.0,92.0,12.709873,11.230926,0
3,32.0,0,122.0,293.0,3,1,1,0,24.130477,1,...,1,1,3,5.249405,3,293.0,94.0,12.509046,5.961958,0
4,60.0,1,166.0,242.0,1,1,1,1,20.486289,1,...,0,1,3,7.030971,3,263.0,154.0,10.381259,8.153887,0
5,25.0,1,152.0,257.0,1,1,0,0,28.144681,0,...,0,1,2,5.504876,1,126.0,91.0,4.297575,10.815983,0

In [24]:
numeric_data = data.select_dtypes(include=['int64', 'float64'])
numeric_data.corr()['Heart Disease Status']

Age                    -0.006233
Blood Pressure         -0.019111
Cholesterol Level       0.008652
BMI                     0.021957
Sleep Hours             0.007656
Triglyceride Level      0.011631
Fasting Blood Sugar     0.001399
CRP Level              -0.005395
Homocysteine Level      0.011784
Heart Disease Status    1.000000
Name: Heart Disease Status, dtype: float64

In [25]:
data.shape

(7067, 21)

In [26]:
X = data.drop('Heart Disease Status', axis=1)
y = data['Heart Disease Status']

In [28]:
%pip install imbalanced-learn
#SMOTE
from imblearn.over_sampling import SMOTE
smote = SMOTE()
x_smote,y_smote = smote.fit_resample(X,y)
y_smote.value_counts()

Collecting imbalanced-learn
  Using cached imbalanced_learn-0.14.1-py3-none-any.whl.metadata (8.9 kB)
Requirement already satisfied: numpy<3,>=1.25.2 in c:\users\gaurawa mihiranga\appdata\local\programs\python\python312\lib\site-packages (from imbalanced-learn) (2.4.6)
Collecting scipy<2,>=1.11.4 (from imbalanced-learn)
  Downloading scipy-1.17.1-cp312-cp312-win_amd64.whl.metadata (60 kB)
Collecting scikit-learn<2,>=1.4.2 (from imbalanced-learn)
  Downloading scikit_learn-1.9.0-cp312-cp312-win_amd64.whl.metadata (11 kB)
Collecting sklearn-compat<0.2,>=0.1.5 (from imbalanced-learn)
  Using cached sklearn_compat-0.1.5-py3-none-any.whl.metadata (20 kB)
Collecting joblib<2,>=1.2.0 (from imbalanced-learn)
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl<4,>=2.0.0 (from imbalanced-learn)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Collecting narwhals>=2.0.1 (from scikit-learn<2,>=1.4.2->imbalanced-learn)
  Using cached narwhals-2.22.0-py3-none-any.whl.metadata (15 kB)
Collecting scikit-learn<2,>=1.4.2 (from imbalanced-learn)
  Downloading scikit_learn-1.8.0-cp312-cp312-win_amd64.whl.metadata (11 kB)
Using cached imbalanced_learn-0.14.1-py3-none-any.whl (235 kB)
Using cached joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading scipy-1.17.1-cp312-cp312-win_amd64.whl (36.5 MB)
   ---------------------------------------- 0.0/36.5 MB ? eta -:--:--
   ---------------------------------------- 0.3/36.5 MB ? eta -:--:--
    --------------------------------------- 0.8/36.5 MB 2.4 MB/s eta 0:00:15
   - -------------------------------------- 1.3/36.5 MB 2.3 MB/s eta 0:00:16
   -- ------------------------------------- 1.8/36.5 MB 2.5 MB/s eta 0:00:14
   -- ------------------------------------- 2.6/36.5 MB 2.8 MB/s eta 0:00:13
   ---- ----------------------------------- 3.7/36.5 MB 3.2 MB/s eta 0:00:11
   ---- ----------------------------------- 4.2/36.5 MB 3.2 MB/s eta 0:00:11
   ----- ---------------------------------- 5.0/36.5 MB 3.1 MB/s eta 0:00:11
   ------ --------------------------------- 5.5/36.5 MB 3.1 MB/s eta 0:00:10
   ------ --------------------------------- 6.0/36.5 MB 3.1 MB/s eta 0:00:10
   ------- -------------------------------- 6.6/36.5 MB 3.0 MB/s eta 0:00:10
   ------- -------------------------------- 7.1/36.5 MB 3.0 MB/s eta 0:00:10
   -------- ------------------------------- 7.9/36.5 MB 3.0 MB/s eta 0:00:10
   --------- ------------------------------ 8.4/36.5 MB 2.9 MB/s eta 0:00:10
   --------- ------------------------------ 8.9/36.5 MB 2.9 MB/s eta 0:00:10
   ---------- ----------------------------- 9.7/36.5 MB 2.9 MB/s eta 0:00:10
   ----------- ---------------------------- 10.5/36.5 MB 3.0 MB/s eta 0:00:09
   ----------- ---------------------------- 10.7/36.5 MB 2.9 MB/s eta 0:00:09
   ------------ --------------------------- 11.3/36.5 MB 2.9 MB/s eta 0:00:09
   ------------ --------------------------- 11.8/36.5 MB 2.9 MB/s eta 0:00:09
   ------------- -------------------------- 12.6/36.5 MB 2.9 MB/s eta 0:00:09
   -------------- ------------------------- 13.4/36.5 MB 2.9 MB/s eta 0:00:08
   --------------- ------------------------ 13.9/36.5 MB 2.9 MB/s eta 0:00:08
   ---------------- ----------------------- 14.7/36.5 MB 2.9 MB/s eta 0:00:08
   ---------------- ----------------------- 15.5/36.5 MB 3.0 MB/s eta 0:00:08
   ----------------- ---------------------- 16.3/36.5 MB 3.0 MB/s eta 0:00:07
   ------------------ --------------------- 17.0/36.5 MB 3.0 MB/s eta 0:00:07
   ------------------- -------------------- 17.6/36.5 MB 3.1 MB/s eta 0:00:07
   -------------------- ------------------- 18.4/36.5 MB 3.0 MB/s eta 0:00:07
   -------------------- ------------------- 18.9/36.5 MB 3.0 MB/s eta 0:00:06
   --------------------- ------------------ 19.4/36.5 MB 3.0 MB/s eta 0:00:06
   --------------------- ------------------ 19.9/36.5 MB 3.0 MB/s eta 0:00:06
   ---------------------- ----------------- 20.4/36.5 MB 3.0 MB/s eta 0:00:06
   ---------------------- ----------------- 21.0/36.5 MB 3.0 MB/s eta 0:00:06
   ----------------------- ---------------- 21.8/36.5 MB 3.0 MB/s eta 0:00:05
   ------------------------ --------------- 22.5/36.5 MB 3.0 MB/s eta 0:00:05
   ------------------------ --------------- 22.8/36.5 MB 3.0 MB/s eta 0:00:05
   ------------------------- -------------- 23.1/36.5 MB 3.0 MB/s eta 0:00:05
   -------------------------- ------------- 23.9/36.5 MB 2.9 MB/s eta 0:00:05
   -------------------------- ------------- 24.6/36.5 MB 2.9 MB/s eta 0:00:05
   --------------------------- ------------ 25.2/36.5 MB 2.9 MB/s eta 0:00:04
   ---------------------------- ----------- 26.0/36.5 MB 2.9 MB/s eta 0:00:04
   ---------------------------- ----------- 26.5/36.5 MB 2.9 MB/s eta 0:00:04
   ----------------------------- ---------- 27.3/36.5 MB 3.0 MB/s eta 0:00:04
   ------------------------------ --------- 27.8/36.5 MB 3.0 MB/s eta 0:00:03
   ------------------------------ --------- 28.3/36.5 MB 3.0 MB/s eta 0:00:03
   ------------------------------- -------- 29.1/36.5 MB 3.0 MB/s eta 0:00:03
   -------------------------------- ------- 29.4/36.5 MB 3.0 MB/s eta 0:00:03
   -------------------------------- ------- 29.9/36.5 MB 2.9 MB/s eta 0:00:03
   -------------------------------- ------- 30.1/36.5 MB 2.9 MB/s eta 0:00:03
   --------------------------------- ------ 30.7/36.5 MB 2.9 MB/s eta 0:00:03
   ---------------------------------- ----- 31.2/36.5 MB 2.9 MB/s eta 0:00:02
   ---------------------------------- ----- 31.7/36.5 MB 2.9 MB/s eta 0:00:02
   ----------------------------------- ---- 32.0/36.5 MB 2.8 MB/s eta 0:00:02
   ----------------------------------- ---- 32.5/36.5 MB 2.8 MB/s eta 0:00:02
   ----------------------------------- ---- 32.8/36.5 MB 2.8 MB/s eta 0:00:02
   ------------------------------------ --- 33.0/36.5 MB 2.8 MB/s eta 0:00:02
   ------------------------------------ --- 33.6/36.5 MB 2.7 MB/s eta 0:00:02
   ------------------------------------- -- 33.8/36.5 MB 2.7 MB/s eta 0:00:01
   ------------------------------------- -- 34.3/36.5 MB 2.7 MB/s eta 0:00:01
   -------------------------------------- - 34.9/36.5 MB 2.7 MB/s eta 0:00:01
   ---------------------------------------  35.7/36.5 MB 2.7 MB/s eta 0:00:01
   ---------------------------------------  36.4/36.5 MB 2.7 MB/s eta 0:00:01
   ---------------------------------------- 36.5/36.5 MB 2.7 MB/s eta 0:00:00
Using cached sklearn_compat-0.1.5-py3-none-any.whl (20 kB)
Downloading scikit_learn-1.8.0-cp312-cp312-win_amd64.whl (8.0 MB)
   ---------------------------------------- 0.0/8.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.0 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.0 MB ? eta -:--:--
   --- ------------------------------------ 0.8/8.0 MB 1.5 MB/s eta 0:00:05
   ----- ---------------------------------- 1.0/8.0 MB 1.5 MB/s eta 0:00:05
   ------ --------------------------------- 1.3/8.0 MB 1.4 MB/s eta 0:00:05
   ------- -------------------------------- 1.6/8.0 MB 1.3 MB/s eta 0:00:05
   ---------- ----------------------------- 2.1/8.0 MB 1.5 MB/s eta 0:00:04
   ----------- ---------------------------- 2.4/8.0 MB 1.4 MB/s eta 0:00:04
   ------------- -------------------------- 2.6/8.0 MB 1.5 MB/s eta 0:00:04
   -------------- ------------------------- 2.9/8.0 MB 1.4 MB/s eta 0:00:04
   ---------------- ----------------------- 3.4/8.0 MB 1.5 MB/s eta 0:00:04
   ------------------- -------------------- 3.9/8.0 MB 1.6 MB/s eta 0:00:03
   ---------------------- ----------------- 4.5/8.0 MB 1.7 MB/s eta 0:00:03
   ------------------------ --------------- 5.0/8.0 MB 1.8 MB/s eta 0:00:02
   --------------------------- ------------ 5.5/8.0 MB 1.8 MB/s eta 0:00:02
   ---------------------------- ----------- 5.8/8.0 MB 1.8 MB/s eta 0:00:02
   -------------------------------- ------- 6.6/8.0 MB 1.9 MB/s eta 0:00:01
   ----------------------------------- ---- 7.1/8.0 MB 1.9 MB/s eta 0:00:01
   ---------------------------------------  7.9/8.0 MB 2.0 MB/s eta 0:00:01
   ---------------------------------------- 8.0/8.0 MB 2.0 MB/s eta 0:00:00
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, joblib, scikit-learn, sklearn-compat, imbalanced-learn
Successfully installed imbalanced-learn-0.14.1 joblib-1.5.3 scikit-learn-1.8.0 scipy-1.17.1 sklearn-compat-0.1.5 threadpoolctl-3.6.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Heart Disease Status
0    5632
1    5632
Name: count, dtype: int64

In [29]:
%pip install sklearn
X = x_smote
y = y_smote

Collecting sklearn
  Using cached sklearn-0.0.post12.tar.gz (2.6 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
Note: you may need to restart the kernel to use updated packages.

  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
      rather than 'sklearn' for pip commands.

      Here is how to fix this error in the main use cases:
      - use 'pip install scikit-learn' rather than 'pip install sklearn'
      - replace 'sklearn' by 'scikit-learn' in your pip requirements files
        (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
      - if the 'sklearn' package is used by one of your dependencies,
        it would be great if you take some time to track which package uses
        'sklearn' instead of 'scikit-learn' and report it to their issue tracker
      - as a last resort, set the environment variable
        SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error

      More information is available at
      https://github.com/scikit-learn/sklearn-pypi-package
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.

[notice] A new release of pip is available: 24.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

In [30]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)

In [31]:
X_train.shape,X_test.shape

((8448, 20), (2816, 20))

In [32]:
def model_acc(model):
    model.fit(X_train,y_train)
    acc = model.score(X_test,y_test)
    print(str(model)+'-->'+str(acc))

In [33]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
model_acc(rf)

from sklearn.svm import SVC
svm = SVC()
model_acc(svm)

from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
model_acc(knn)

from sklearn.naive_bayes import GaussianNB
nb = GaussianNB()
model_acc(nb)

from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(max_iter=1000)
model_acc(lr)

from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier()
model_acc(dt)

RandomForestClassifier()-->0.86328125
SVC()-->0.5106534090909091
KNeighborsClassifier()-->0.7290482954545454
GaussianNB()-->0.7354403409090909
LogisticRegression(max_iter=1000)-->0.5205965909090909
DecisionTreeClassifier()-->0.7844460227272727

c:\Users\Gaurawa Mihiranga\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [34]:
from sklearn.model_selection import GridSearchCV

param_grid = {
    'n_estimators': [50, 100, 200],
    'max_depth': [None, 10, 20, 30],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

grid_obj = GridSearchCV(
    estimator=rf,
    param_grid=param_grid,
    cv=5,
    scoring='accuracy',
    n_jobs=-1,
    verbose=1
)

grid_fit = grid_obj.fit(X_train,y_train)

best_model = grid_fit.best_estimator_
best_model

Fitting 5 folds for each of 108 candidates, totalling 540 fits

RandomForestClassifier(max_depth=30, min_samples_leaf=2, min_samples_split=5)

In [35]:
best_model.score(X_test,y_test)

0.86328125

In [36]:
import pickle

with open('predictor.pickle', 'wb') as file:
    pickle.dump(best_model, file)

In [37]:
X_train.columns

Index(['Age', 'Gender', 'Blood Pressure', 'Cholesterol Level',
       'Exercise Habits', 'Smoking', 'Family Heart Disease', 'Diabetes', 'BMI',
       'High Blood Pressure', 'Low HDL Cholesterol', 'High LDL Cholesterol',
       'Alcohol Consumption', 'Stress Level', 'Sleep Hours',
       'Sugar Consumption', 'Triglyceride Level', 'Fasting Blood Sugar',
       'CRP Level', 'Homocysteine Level'],
      dtype='str')

In [38]:
y_pred = best_model.predict(X_test)

In [39]:
print(y_pred[:20])

[0 0 1 0 0 0 0 0 1 0 0 1 1 0 0 0 0 0 1 0]

In [40]:
print(y_test[:20])

1143     0
2838     0
8324     1
2718     0
4122     0
5184     0
2281     0
5279     0
10685    1
7039     1
4449     0
9440     1
9446     1
4591     0
4160     0
5054     0
5631     0
5945     1
9631     1
5232     0
Name: Heart Disease Status, dtype: int64

In [41]:
row = data.iloc[5675]

# Convert to NumPy array
row_array = row.to_numpy()    # 1D array
print(row_array)

[np.float64(27.0) 0 np.float64(131.0) np.float64(185.0) 3 0 0 1
 np.float64(31.82638424) 1 0 1 1 2 np.float64(9.750090491) 1
 np.float64(132.0) np.float64(129.0) np.float64(3.644901285)
 np.float64(5.614354603) np.int64(1)]

In [42]:
data.head()

,Age,Gender,Blood Pressure,Cholesterol Level,Exercise Habits,Smoking,Family Heart Disease,Diabetes,BMI,High Blood Pressure,...,High LDL Cholesterol,Alcohol Consumption,Stress Level,Sleep Hours,Sugar Consumption,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level,Heart Disease Status
1,69.0,0,146.0,286.0,3,0,1,1,25.221799,0,...,0,2,3,8.744034,2,133.0,157.0,9.355389,19.298875,0
2,46.0,1,126.0,216.0,1,0,0,0,29.855447,0,...,1,1,1,4.440440,1,393.0,92.0,12.709873,11.230926,0
3,32.0,0,122.0,293.0,3,1,1,0,24.130477,1,...,1,1,3,5.249405,3,293.0,94.0,12.509046,5.961958,0
4,60.0,1,166.0,242.0,1,1,1,1,20.486289,1,...,0,1,3,7.030971,3,263.0,154.0,10.381259,8.153887,0
5,25.0,1,152.0,257.0,1,1,0,0,28.144681,0,...,0,1,2,5.504876,1,126.0,91.0,4.297575,10.815983,0

In [43]:
test_sample = [
    [27.0, 0, 131.0, 185.0, 3.0, 0.0, 0.0, 1.0, 31.826384, 1.0, 0.0, 1.0, 1.0, 2.0, 9.75009049, 1.0, 132.0, 129.0, 3.64490128, 5.6143546]

]

results = best_model.predict(test_sample)
print(results)

[1]

c:\Users\Gaurawa Mihiranga\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(